### ISSUE TITLE
Setup of Account for New API

### ISSUE THREAD

**Issue by consultantRR** [jimmycuadra/lita-google-images#6]
This is probably an incredibly daft question, but can someone clarify what exactly needs to be done within Google to set up an account for the new API to work?

I have set up a new search engine here:
https://cse.google.com/cse/setup/basic

I have taken the search engine ID from there, and created an API key. The pair of these seem to work within `lita-google-images` in that I don't get errors in the logs when calling `lita image foo`.

I do however get this response every time:

```
No images found for "foo".
```

Within the Google interface, I have turned "Image Search" on, and I have added "images.google.com" under "Sites to Search".

Any further guidance on this?

**Comment by HugoTamaki** [comment]
![captura de tela 2015-12-23 as 20 03 17](https://cloud.githubusercontent.com/assets/5509842/11985857/48ab9986-a9b0-11e5-8ffa-cc7b30b4bc4d.png)

@consultantRR, 
You don't need to set any sites to search. Instead, try to set the select input as "Search the entire web but emphasize included sites".

**Comment by consultantRR** [comment]
That worked, thanks! Maybe I will submit a PR to include this in the documentation. IMO, Google is not at all clear about the setup on the API side.

**Comment by cjbottaro** [comment]
@HugoTamaki What page is that UI from?  All I'm seeing is this:  http://d.pr/i/1hjW1  and there is no option to "search the entire web".

Yes, documentation definitely needs the whole "setup Google Custom Search" thing.
